### PR TITLE
Plot outputs incorrectly sized inside scaled outputs

### LINKED ISSUE #4135: Plot outputs incorrectly sized inside scaled outputs
When plot outputs appear inside scaled regions of the DOM, Shiny reports the output area in absolute pixels (i.e. the size of the output area _after_ the scaling is applied). The returned image, however, ends up being smaller than desired because it doesn't take into account the scaling.

You can see this happening in the [superzip example](https://testing-apps.shinyapps.io/063-superzip-example/).

image

I've applied a red outline to the plot output area and a blue outline to the actual image. Ideally these would overlap and the image would take up the full output area.

<details>
<summary>CSS</summary>

```css
.shiny-plot-output {
    outline: 1px solid red;
}

.shiny-plot-output > img {
    outline: 1px solid blue;
}
```

</details>

In this example, on app load, the `histCentile` output reports size 259 x 180px and receives an image with those dimensions. But the output appears in an absolute panel (`#controls`) that has `zoom: 0.9` applied. Those are indeed the absolute dimensions of the `#histCentile` container _after_ the browser has scaled the output container. Once placed, the image ends up with the absolute size of 233.09 x 162px. The image should instead be 287.78 x 200px (taking into account the scaling) to end up with the correct size.

### PR DESCRIPTION
**Pull request by jcheng5**
Fixes #4135.

CSS zoom property affects `el.getBoundingClientRect()` but not `el.offsetWidth/Height`. When reporting sizes of outputs from client to server, we need to back out the CSS zoom because those sizes are used as CSS width/height, which will be affected by zoom.

(Note that something similar happens with CSS transforms but we don't have a good way to deal with them)

Safari doesn't support `el.currentCSSZoom`, but it also doesn't have the problem of `el.getBoundingClientRect()` and offset size not matching when zoom is applied. We're hoping that these two facts are not a coincidence and that any browser that treats those sizes as different also gives us `el.currentCSSZoom`.

getBoundingClientRect is also used in the coordmap for plots. @gadenbuie and I verified that coordmaps already work well even when zoom is applied. The `coords_css` uses `el.getBoundingClientRect()` without backing out the zoom; I'm convinced this is correct/how it has to be.

### CODE REVIEW

File: srcts/src/utils/index.ts [hunk 1]
```diff
@@ -144,6 +144,19 @@ function pixelRatio(): number {
   }
 }
 
+function getBoundingClientSizeBeforeZoom(el: HTMLElement): {
+  width: number;
+  height: number;
+} {
+  const rect = el.getBoundingClientRect();
+  // Cast to any because currentCSSZoom isn't in the type def of HTMLElement
+  const zoom = (el as any).currentCSSZoom || 1;
```
Comment (gadenbuie) [inline srcts/src/utils/index.ts:153]: `currentCSSZoom` was added in typescript release 5.5.2 ([here's the commit](https://github.com/microsoft/TypeScript/commit/e04a27c50427013f9ea768f35c9199d27ecfdaef#diff-dc0eab937d15e62545da3ed7b4f40ad6b24f15dd88fbc6ceda2bfb4ed8356eb0R5085)); worth adding a TODO and hope we catch this in the future.

```suggestion
  // Cast to any because currentCSSZoom isn't in the type def of HTMLElement
  // TODO: typescript >= 5.5.2 added this property to the type definition
  const zoom = (el as any).currentCSSZoom || 1;
```

**Review by gadenbuie — APPROVED** [review]
LGTM! It seems that `currentCSSZoom` will be available when we update typescript to >= 5.5.2.
