### PR TITLE
Fix rlang::inject with render functions

### LINKED ISSUE #3374: rlang::inject() with renderFunction() don't work with nested quosures
```r
> quoA <- rlang::quo(1)
> quoB <- rlang::quo(1 + !!quoA)
> rlang::inject(shiny::renderText(!!quoB))()
Error: Base operators are not defined for quosures.
Do you need to unquote the quosure?

  # Bad:
  lhs + myquosure

  # Good:
  lhs + !!myquosure
```

As explained in more detail here https://github.com/rstudio/shiny/pull/3361#issuecomment-820672180, this isn't a problem for `reactive()` or `observe()` since those use `as_function()` instead of `new_function()`.

### PR DESCRIPTION
**Pull request by jcheng5**
Closes #3374

### CODE REVIEW

**Review by wch — APPROVED** [review]
Looks good! Can you add a NEWS item?

**Review by wch — APPROVED** [review]

File: R/utils.R [hunk 1]
```diff
@@ -538,9 +538,7 @@ installExprFunction <- function(expr, name, eval.env = parent.frame(2),
 #' @export
 quoToFunction <- function(q, label, ..stacktraceon = FALSE) {
   q <- as_quosure(q)
-  # Use new_function() instead of as_function(), because as_function() adds an
-  # extra parent environment. (This may not actually be a problem, though.)
-  func <- new_function(NULL, get_expr(q), get_env(q))
+  func <- as_function(q)
```
Comment (wch) [inline R/utils.R:541]: Note that this is causing a test failure because the old code creates a function with the signature `function()`, but the new code creates a function with the signature `function(...)`. I don't think that the added `...` currently cause any problems right now (other than the test failure), but in order to keep the code tighter, I think we should remove them. I can make the change.
