### PR TITLE
Change the evaluation rules for the icon promise in downloadButton()

### LINKED ISSUE #3022: downloadButton promise already under evaluation
### System details

In RStudio Cloud, August 27th, 2020.

<details> 
<summary>Output of `sessionInfo()`: </summary>

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8   
 [6] LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C           LC_TELEPHONE=C        
[11] LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5            tidyr_1.1.2           prettyunits_1.1.1     ps_1.3.4              visNetwork_2.1.0     
 [6] assertthat_0.2.1      rprojroot_1.3-2       digest_0.6.25         mime_0.9              R6_2.4.1             
[11] backports_1.1.9       httr_1.4.2            ggplot2_3.3.2         pillar_1.4.6          rlang_0.4.7          
[16] shinyalert_1.1        lazyeval_0.2.2        gfpop_0.2.2           curl_4.3              rstudioapi_0.11      
[21] data.table_1.13.0     callr_3.4.3           DT_0.15               gfpopgui_0.1.0        shinythemes_1.1.2    
[26] shinyjs_1.1           config_0.3            desc_1.2.0            devtools_2.3.1        stringr_1.4.0        
[31] htmlwidgets_1.5.1     munsell_0.5.0         shiny_1.5.0.9001      xfun_0.16             compiler_4.0.2       
[36] httpuv_1.5.4          pkgconfig_2.0.3       pkgbuild_1.1.0        htmltools_0.5.0       tidyselect_1.1.0     
[41] tibble_3.0.3          roxygen2_7.1.1        attempt_0.3.1         fansi_0.4.1           viridisLite_0.3.0    
[46] crayon_1.3.4          dplyr_1.0.2           withr_2.2.0           later_1.1.0.1         grid_4.0.2           
[51] jsonlite_1.7.0        xtable_1.8-4          gtable_0.3.0          lifecycle_0.2.0       magrittr_1.5         
[56] dockerfiler_0.1.3     scales_1.1.1          cli_2.0.2             stringi_1.4.6         fs_1.5.0             
[61] promises_1.1.1        remotes_2.2.0         testthat_2.3.2        xml2_1.3.2            ellipsis_0.3.1       
[66] generics_0.0.2        vctrs_0.3.2           tools_4.0.2           golem_0.2.1           glue_1.4.2           
[71] purrr_0.3.4           crosstalk_1.1.0.1     shinycssloaders_1.0.0 processx_3.4.3        pkgload_1.1.0        
[76] fastmap_1.0.1         yaml_2.2.1            colorspace_1.4-1      sessioninfo_1.1.1     memoise_1.1.0        
[81] plotly_4.9.2.1        knitr_1.29            usethis_1.6.1 
```
</details>

### Steps to reproduce the problem

In Shiny version 1.5.0.9001:

```R
> shiny::downloadButton("downloadData")
Error in validateIcon(icon) : 
  promise already under evaluation: recursive default argument reference or earlier problems?
```

### Describe the problem in detail

The new dev version of shiny was breaking for my UI. I was getting a weird error "promise already under evaluation" which traced back to `shiny::downloadButton()`.

I think this has something to do with 7b43617954619d2bc74eee6f113c65f581e99aea? @ColinFay 

Because of the addition of `validateIcon(icon)` and `icon = icon("download")`.

As expected, `shiny::downloadButton("downloadData", icon = NULL)` does not throw an error. 

I don't fully understand the problem, but I wanted to post it here in case this would also be a breaking change for other people. 

Thanks! :)

### PR DESCRIPTION
**Pull request by cpsievert**
Fixes #3022

### CODE REVIEW

**Comment by wch** [comment]
I think it would be more straightforward to just use a default of `icon = shiny::icon("download")` -- then there's no need for `eval()`.

File: R/bootstrap.R [hunk 1]
```diff
@@ -1346,6 +1346,12 @@ downloadButton <- function(outputId,
                            class=NULL,
                            ...,
                            icon=icon("download")) {
```
Comment (schloerke) [inline R/bootstrap.R:1348]:
```suggestion
                           icon = shiny::icon("download")) {
```

File: R/bootstrap.R [hunk 2]
```diff
@@ -1346,6 +1346,12 @@ downloadButton <- function(outputId,
...
+  # Avoid recursive default argument reference
+  icon <- eval(
+    substitute(icon),
+    list(outputId = outputId, label = label, class = class, ...),
+    parent.frame()
+  )
```
Comment (schloerke) [inline R/bootstrap.R:1354]:
```suggestion
```
