### PR TITLE
Fix html tags in tab titles

### LINKED ISSUE #3352: Tab titles with html tag objects are not rendered properly
Example:

```R
shinyApp(
  fluidPage(
    tabsetPanel(
      tabPanel(tagList(icon("calendar"), "Calendar"), "content"),
      tabPanel("Summary", "content")
    )
  ),
  function(input, output) {}
)
```

In Shiny 1.6.0, this is what it looks like:

image

In the dev version (currently 268c9afe):

image

This was introduced by #3315.

### PR DESCRIPTION
**Pull request by wch**
This fixes #3352. 

Testing notes: For a test app, see that issue. This PR also has a unit test.

### CODE REVIEW

**Review by cpsievert — APPROVED** [review]

File: R/bootstrap.R [hunk 1]
```diff
@@ -1013,7 +1013,10 @@ buildTabItem <- function(index, tabsetId, foundSelected, tabs = NULL,
 
 buildNavItem <- function(divTag, tabsetId, index) {
   id <- paste("tab", tabsetId, index, sep = "-")
-  title <- tagGetAttribute(divTag, "title")
+  # Get title attribute directory (not via tagGetAttribute()) so that contents
+  # don't get passed to as.character().
+  # https://github.com/rstudio/shiny/issues/3352
+  title <- divTag$attribs$title
   value <- tagGetAttribute(divTag, "data-value")
```
Comment (cpsievert) [inline R/bootstrap.R:1020]: Do you know if this was also changed (looking now)?

Comment (cpsievert) [reply R/bootstrap.R:1020]: Yea looks like it https://github.com/rstudio/shiny/pull/3315/files#diff-befe9146792f0d65aeeaf781e8ba00a1a3638ac2be162b61b6c8958440860b56L986

Comment (cpsievert) [inline R/bootstrap.R:1020]:
```suggestion
  value <- divTag$attribs[["data-value"]]
```

File: R/bootstrap.R [hunk 2]
```diff
@@ -1013,7 +1013,10 @@ buildTabItem <- function(index, tabsetId, foundSelected, tabs = NULL,
...
   icon <- getIcon(iconClass = tagGetAttribute(divTag, "data-icon-class"))
```
Comment (cpsievert) [inline R/bootstrap.R:1021]:
```suggestion
  icon <- getIcon(iconClass = divTag$attribs[["data-icon-class"]])
```
