### PR TITLE
Correctly render script tags defined as list() objects

### LINKED ISSUE #3345: htmlDependency used in dynamic UI breaks when `script` is provided as a named list instead of a string
Not sure if this should be filed under {htmltools} or {shiny} - I filed it here because the interaction with shiny is what's broken from what I can tell.

To use `htmlDependency` to load a javascript module, we need to use `script = list(src = "test.js", type = "module")`. This works fine when the dependency is resolved from the UI, but it seems to parse incorrectly when done dynamically. Example:

```
library(shiny)

ui <- fluidPage(
  htmltools::attachDependencies(
    "test",
    htmltools::htmlDependency(
      name = "test",
      version = "1.0.0",
      src = c(href = "https://cdn.jsdelivr.net/gh/daattali/htmldependencybug"),
      script = list(src = "test.js", type = "module")
    )
  )
)

server <- function(input, output, session) {
}

shinyApp(ui, server)
```

The above code works - you'll see a javascript alert.

But if the content is loaded dynamically -- either using insertUI or using a uiOutput/renderUI -- then it breaks. Example:

```
library(shiny)

ui <- fluidPage(
  uiOutput("test")
)

server <- function(input, output, session) {
  output$test <- renderUI({
    htmltools::attachDependencies(
      "test",
      htmltools::htmlDependency(
        name = "test",
        version = "1.0.0",
        src = c(href = "https://cdn.jsdelivr.net/gh/daattali/htmldependencybug"),
        script = list(src = "test.js", type = "module")
      )
    )
  })
}

shinyApp(ui, server)
```

The page loads but the javascript module isn't loaded. Looking at the page source, I can see that it's trying to load a script with src of `https://cdn.jsdelivr.net/gh/daattali/htmldependencybug/%5Bobject%20Object%5D` - this is what's causing this bug. It seems that shiny does not know how to deal with the `script` argument being a named list, even though a named list is  allowed according to the documentation.

### PR DESCRIPTION
**Pull request by cpsievert**
Closes #3345

### CODE REVIEW

File: srcts/src/main.ts [hunk 1]
```diff
@@ -4155,8 +4156,23 @@ function main(): void {
...
+        const attrs = typeof x === "string" ? "src" : Object.keys(x);
+        let script = $("<script>");
+
+        for (let i = 0; i < attrs.length; i++) {
+          const nm = attrs[i];
+          const val = x[nm];
+
+          nm === "src"
+            ? script.attr("src", href + "/" + encodeURI(val))
+            : script.attr(nm, val);
```
Comment (cpsievert) [inline srcts/src/main.ts:4172]: TODO: do we need to worry about security implications?

File: srcts/src/main.ts [hunk 2]
```diff
@@ -4155,8 +4155,28 @@ function main(): void {
...
+        for (let i = 0; i < attrs.length; i++) {
+          const attr = attrs[i];
+          let val = x[attr];
+
+          if (attr === "src") {
+            val = href + "/" + encodeURI(val);
+          }
+          // If val isn't truthy (e.g., null), consider it a boolean attribute
+          val ? script.setAttribute(attr, val) : script.toggleAttribute(attr);
+        }
```
Comment (schloerke) [inline srcts/src/main.ts:4177]: Leverage jquery for the for-loop;
`toggleAttribute()` is not IE friendly.

```suggestion
        $.map(attrs, function(val, attr) {

          if (attr === "src") {
            val = href + "/" + encodeURI(val);
          }
          // If val isn't truthy (e.g., NA), only set the key
          script.setAttribute(attr, val ? val : "")
        })
```

Comment (schloerke) [reply srcts/src/main.ts:4177]: https://caniuse.com/?search=toggleAttribute

**Comment by schloerke** [comment]
Tested and works with @daattali 2nd example in https://github.com/rstudio/shiny/issues/3345#issue-839301034
Screen Shot 2021-05-19 at 5 45 54 PM

**Review by schloerke — APPROVED** [review]
LGTM given suggestion; Errors are unrelated to PR

**Comment by daattali** [comment]
Do you know if I can install shiny from this PR to check for my more complex usecase that it works? `remotes::install_github("https://github.com/rstudio/shiny", ???)`

**Comment by schloerke** [comment]
@daattali 

> Do you know if I can install shiny from this PR to check for my more complex usecase that it works? `remotes::install_github("https://github.com/rstudio/shiny", ???)`

```r
remotes::install_github("rstudio/shiny#3395")
```

**Comment by schloerke** [comment]
@daattali Please let us know if there are any more changes needed and/or if you have more complicated reprex apps to test.

We'll merge after we receive your confirmation. 😃

**Comment by daattali** [comment]
I can verify it works for my more complex usecase https://github.com/daattali/shinywc/issues/13

**Comment by daattali** [comment]
(I'd also like to untactfuly hijack this PR to see if https://github.com/rstudio/shiny/issues/1545 can also be tackled as it seems potentially related)

**Comment by cpsievert** [comment]
#1545 should be handled in a different PR -- it's not related to this same code path

File: srcts/src/main.ts [hunk 3]
```diff
@@ -4155,8 +4155,28 @@ function main(): void {
...
+        for (let i = 0; i < attrs.length; i++) {
+          const attr = attrs[i];
+          let val = x[attr];
+
+          if (attr === "src") {
+            val = href + "/" + encodeURI(val);
+          }
+          // If val isn't truthy (e.g., null), consider it a boolean attribute
+          script.setAttribute(attr, val ? val : "");
+        }
```
Comment (wch) [inline srcts/src/main.ts:4177]: I think you may be able to replace this with:

```suggestion
        for (let [attr, val] of Object.entries(x)) {
          if (attr === "src") {
            val = href + "/" + encodeURI(val);
          }
          // If val isn't truthy (e.g., null), consider it a boolean attribute
          script.setAttribute(attr, val ? val : "");
        }
```

See https://effectivetypescript.com/2020/05/26/iterate-objects/

@schloerke, @nstrayer, it would be great if you guys could weigh in on this.

Comment (schloerke) [reply srcts/src/main.ts:4177]: A polyfill for `Object.entries` will be required (IE / Phantom), but it is more succinct

(Changed the proposed to a `const` instead of a `let` in the for loop.)

```suggestion
        for (const [attr, val] of Object.entries(x)) {
          if (attr === "src") {
            val = href + "/" + encodeURI(val);
          }
          // If val isn't truthy (e.g., null), consider it a boolean attribute
          script.setAttribute(attr, val ? val : "");
        }
```

Comment (wch) [reply srcts/src/main.ts:4177]: With `const [attr, val]`, isn't that a problem for `val = href + "/" + encodeURI(val)`?

Comment (wch) [reply srcts/src/main.ts:4177]: Also, IMO, it's not worth adding a polyfill for this.
