### PR TITLE
Properly handle undefined value for input subscribe callback

### LINKED ISSUE #4240: airDatepickerInput reactivity not working properly in Shiny 1.11.0
# Bug Report: airDatepickerInput reactivity not working properly in Shiny 1.11.0

## Description
The `airDatepickerInput` from the `shinyWidgets` package is not triggering reactive outputs properly in Shiny version 1.11.0. The reactive expressions that depend on the input are not updating when the date picker value changes.

## Expected Behavior
When selecting a month using `airDatepickerInput`, the reactive outputs should update immediately to reflect the new selected value.

## Actual Behavior
The reactive outputs do not update when the date picker value changes. The inputs appear to be registered but do not trigger the reactive chain properly.

## System Information
- **Shiny version**: 1.11.0 (issue present)
- **Shiny version**: 1.10.0 (working correctly)
- **shinyWidgets version**: 0.9.0
- **R version**: 4.3.1

## Reproducible Example

```r
library(shiny)
library(shinyWidgets)

# UI
ui <- fluidPage(
  titlePanel("Shiny App with airDatePicker"),
  
  sidebarLayout(
    sidebarPanel(
      h4("Select a month:"),
      airDatepickerInput(
        inputId = "fecha_seleccionada",
        label = "Month:",
        value = Sys.Date(),
        view = "months",
        minView = "months",
        dateFormat = "MM yyyy"
      )
    ),
    
    mainPanel(
      h4("Selected Month:"),
      verbatimTextOutput("mostrar_fecha"),
      
      br(),
      
      h4("Additional Information:"),
      textOutput("info_fecha")
    )
  )
)

# Server
server <- function(input, output) {
  
  # Show the selected month
  output$mostrar_fecha <- renderText({
    if(!is.null(input$fecha_seleccionada)) {
      paste("Month:", format(input$fecha_seleccionada, "%B %Y"))
    } else {
      "No month selected"
    }
  })
  
  # Additional information about the month
  output$info_fecha <- renderText({
    if(!is.null(input$fecha_seleccionada)) {
      year <- format(input$fecha_seleccionada, "%Y")
      month_num <- format(input$fecha_seleccionada, "%m")
      paste("Year:", year, "| Month number:", month_num)
    }
  })
}

# Run the application
shinyApp(ui = ui, server = server)
```

## Steps to Reproduce
1. Run the provided example code
2. Select a different month using the date picker
3. Observe that the text outputs do not update

## Workaround
Downgrading to Shiny version 1.10.0 resolves the issue.

## Additional Notes
This appears to be a regression introduced in Shiny 1.11.0. The issue specifically affects `airDatepickerInput` from the `shinyWidgets` package, though other input widgets from the same package may also be affected.

The input value is being captured (as evidenced by the initial render), but subsequent changes do not trigger the reactive chain properly.

Image

### PR DESCRIPTION
**Pull request by cpsievert**
Closes #4240

This regression was introduced by #4211, where support for new values for added to `InputBinding.subscribe()`'s `callback`. There, I overlooked the fact that we did support no value (i.e., `undefined`) passed to the `.callback()`, but the new code wouldn't handle it properly.

Now we properly handle an `undefined` value (and also type that case properly)

### CODE REVIEW

File: srcts/src/shiny/bind.ts [hunk 1]
```diff
@@ -264,13 +264,13 @@ function bindInputs(
         const thisBinding = binding;
         const thisEl = el;
 
-        return function (priority: SubscribeEventPriority) {
+        return function (priority: SubscribeEventPriority | undefined) {
```
Comment (gadenbuie) [inline srcts/src/shiny/bind.ts]: I think it might be worth doing a little refactoring here, plus some runtime value checks (since most user code won't be written in Typescript).

```ts
function normalizeEventPriority(
  priority?: SubscribeEventPriority
): EventPriority {
  if (priority !== null && typeof priority === "object") {
    if ("priority" in priority) {
      return normalizeEventPriority(priority.priority); // recurse for value check
    }
    return "immediate";
  }

  if (typeof priority === "string") {
    switch (priority) {
      case "immediate":
      case "deferred":
      case "event":
        return priority;
      default:
        throw new Error(`Unknown event priority: ${priority}`);
    }
  }

  // Support historical boolean or missing values
  return priority ? "deferred" : "immediate";
}
```

This function could be included where the `SubscribeEventPriority` type is defined, where there's also a helpful comment giving some of the background. I think it's worth having all of that in one place.

That would simplify the code here to just

```ts
return function (priority: SubscribeEventPriority | undefined) {
  const normalizedPriority = normalizeEventPriority(priority);
  valueChangeCallback(inputs, thisBinding, thisEl, normalizePriority);
};
```

**Review by jonthegeek — COMMENTED** [review]
This fixes issues I have with 1.11.0 (other than the issue from #4242). Can you add a test so this bug doesn't make it to CRAN again? It looks like {shinyWidgets} also lacks a lot of tests, so that's how this made it through without revdeps catching it.

File: srcts/src/shiny/bind.ts (hunk 1 above)
Comment (cpsievert) [reply srcts/src/shiny/bind.ts]: I took a slightly different approach in [61053df](https://github.com/rstudio/shiny/pull/4243/commits/61053df0f7b649916d5583dcecad4cf7410d7e5c) -- also, `.setInput()` already has a runtime check
