### PR TITLE
Bookmarking fixes

### LINKED ISSUE #1273: Remaining bookmarkable state issues
- [x] The `onBookmark`, `onBookmarked`, `onRestore`, and `onRestored` observers should print errors and stack trace to the console. UPDATE: It turns out that they already do this.
- [x]  In `ReactiveValues`, the `invalidate` and `uninvalidate` should be renamed to something less confusing.
- [x]  Calling `updateXxxInput` functions inside of the `onRestored` callback doesn't work because it puts things the `inputMessageQueue` after `session$flushOutput()` is called, but there's no `msg` to trigger another flush.

### PR DESCRIPTION
**Pull request by wch**
This closes #1273.

### CODE REVIEW

File: R/shiny.R [hunk 1]
```diff
@@ -962,20 +962,37 @@ ShinySession <- R6Class(
...
+          length(private$inputMessageQueue) != 0
+        )
+      }
+
       # ..stacktraceon matches with the top-level ..stacktraceoff..
       private$flushCallbacks$invoke(..stacktraceon = TRUE)
-      # ..stacktraceon matches with the top-level ..stacktraceoff..
-      on.exit(private$flushedCallbacks$invoke(..stacktraceon = TRUE))
 
-      if (length(private$progressKeys) == 0
```
Comment (wch) [inline R/shiny.R]: Previously, the check for `private$progressKeys` didn't quite have the right logic, I believe. If there was anything in `private$progressKeys`, *all* of the subsequent code in this function would run, including sending a message that didn't contain anything from `private$progressKeys`:

```R
 private$sendMessage(
         errors = as.list(errors),
         values = as.list(values),
         inputMessages = inputMessages
       )
```

I think that instead, `private$progressKeys` should just get reset every time this function is called. (That's how I've implemented it, below.)

**Comment by wch** [comment]
This should be good to merge now.

File: R/shiny.R [hunk 2]
```diff
@@ -1552,17 +1568,37 @@ outputOptions <- function(x, name, ...) {
 #'
 #' @export
 onFlush <- function(fun, once = TRUE, session = getDefaultReactiveDomain()) {
-  session$onFlush(fun)
+  session$onFlush(fun, once = once)
```
Comment (jcheng5) [inline R/shiny.R]: Heh, good catch

File: R/shiny.R [hunk 3]
```diff
@@ -961,21 +958,40 @@ ShinySession <- R6Class(
...
+        if (hasPendingUpdates() || .getReactiveEnvironment()$hasPendingFlush()) {
+          scheduleFlush()
+        }
+      })
 
+      # Clear any progress keys
       private$progressKeys <- character(0)
 
+      if (!hasPendingUpdates()) {
+        return(invisible())
```
Comment (jcheng5) [inline R/shiny.R]: It actually may not be safe to return early here. I think shiny.js treats the reception of an errors/values message (can't remember which) as an indication that the flushReact loop has completed, and uses that knowledge to stop showing progress.

Comment (jcheng5) [inline R/shiny.R]: https://github.com/rstudio/shiny/blob/master/inst/www/shared/shiny.js#L1023-L1025

File: R/shiny.R (hunk 1 above)
Comment (jcheng5) [inline R/shiny.R]: The original code was correct. The existence of progress keys means we need to send a `values` message (even if empty) as this has a side effect of clearing out progress indication on the client. See the other note I added.

**Comment by jcheng5** [comment]
Other than those progress-related fixes that need to be made, this looks good. Let me review one more time after you fix those.

**Comment by wch** [comment]
OK, I've restored the original logic for `progressKeys`.
