### PR TITLE
Put pre-Chromium Edge in the same category as IE

### LINKED ISSUE #3219: setCurrentTheme() doesn't work with non-Chromium Edge
1. Run ` bs_theme_preview(bs_theme())` on Windows IDE and Open the themer demo app on "Edge" browser
                     or
1. Open https://testing-apps.shinyapps.io/shinyapps-themer-demo-Dec-16/ on Edge
2. Update some themer settings -> themes, colors, fonts etc

Expected: App or page should update with the new settings
Actual: Notice the page is displayed something like below and does not automatically refresh with the new CSS changes. Page needs to be manually refreshed for the app the take in the new settings.

Windows_edge_page_load_with_themer_customizations

edge_console_themer_demo

### PR DESCRIPTION
**Pull request by cpsievert**
Closes #3219

## Testing notes

Install an older (lower than 79) version of Edge and run the following. When you click the checkbox the background should turn black

```r
library(shiny)
library(bslib)
light <- bs_theme()
dark <- bs_theme(bg = "black", fg = "white", primary = "purple")
ui <- fluidPage(
  theme = light,
  checkboxInput("dark_mode", "Dark mode", value = FALSE)
)
server <- function(input, output, session) {
  observe({
    session$setCurrentTheme(
      if (isTRUE(input$dark_mode)) dark else light
    )
  })
}
shinyApp(ui, server)
```

### CODE REVIEW

File: srcjs/browser.js [hunk 1]
```diff
@@ -13,9 +13,9 @@ var browser = (function() {
     $(document.documentElement).addClass('qt5');
   }
 
-  // Detect IE information
+  // Detect IE and older (pre-Chromium) Edge
   var ua = window.navigator.userAgent;
-  var isIE = /MSIE|Trident/.test(ua);
+  var isIE = /MSIE|Trident/.test(ua) || ua.indexOf("Edge") > -1;
```
Comment (wch) [inline srcjs/browser.js:18]:
```suggestion
  var isIE = /MSIE|Trident|Edge/.test(ua);
```

**Review by wch — APPROVED** [review]
