### PR TITLE
Fix use of shinyOptions in modules

### LINKED ISSUE #3112: Setting shinyOptions() inside a module results in error
Here's a minimal example:

```r
library(shiny)

my_ui <- function(id) {
  ns <- NS(id)
  div(id = ns(id))
}

my_server <- function(id) {
  moduleServer(id, function(input, output, session) {
    shinyOptions("my_option" = 2)
  })
}

shinyApp(
  fluidPage(my_ui("foo")),
  function(input, output, session) {
    my_server("foo")
  }
)
```

```r
Listening on http://127.0.0.1:4969
Warning: Error in $<-.session_proxy: Attempted to assign value on session proxy.
  66: stop
  65: $<-.session_proxy [/Users/cpsievert/github/shiny/R/modules.R#34]
  63: shinyOptions [/Users/cpsievert/github/shiny/R/shiny-options.R#181]
  62: module [#3]
  57: callModule [/Users/cpsievert/github/shiny/R/modules.R#167]
  56: moduleServer [/Users/cpsievert/github/shiny/R/modules.R#140]
  55: my_server [#2]
  54: server [#4]
Error in `$<-.session_proxy`(`*tmp*`, "options", value = list(appToken = "3519025a595dc742",  : 
  Attempted to assign value on session proxy.
```

### PR DESCRIPTION
**Pull request by wch**
Closes #3112.

The test app below should show "This is my_option" and "This is my_option_nested" in the text boxes.

```R
library(shiny)

my_ui <- function(id) {
  ns <- NS(id)
  verbatimTextOutput(ns("txt"), placeholder = TRUE)
}

my_server <- function(id, nested = FALSE) {
  moduleServer(id, function(input, output, session) {
    if (nested) {
      str(getCurrentOutputInfo())
      shinyOptions("my_option_nested" = "This is my_option_nested")
      output$txt <- renderText(getShinyOption("my_option_nested"))
    } else {
      shinyOptions("my_option" = "This is my_option")
      output$txt <- renderText(getShinyOption("my_option"))
    }
  })
}


my_ui_nested <- function(id) {
  ns <- NS(id)
  my_ui(ns(id))
}
my_server_nested <- function(id) {
  moduleServer(id, function(input, output, session) {
    my_server(id, TRUE)
  })
}

shinyApp(
  fluidPage(
    my_ui("one"),
    my_ui_nested("two")
  ),
  function(input, output, session) {
    my_server("one")
    my_server_nested("two")
  }
)
```

Note: test app has been added in https://github.com/rstudio/shinycoreci-apps/pull/81

### CODE REVIEW

File: R/modules.R [hunk 1]
```diff
@@ -31,6 +31,14 @@ createSessionProxy <- function(parentSession, ...) {
   # but not `session$userData <- TRUE`) from within a module
   # without any hacks (see PR #1732)
   if (identical(x[[name]], value)) return(x)
+
+  # Special case for $options (issue #3112)
+  if (name == "options") {
+    parent <- .subset2(x, "parent")
```
Comment (schloerke) [inline R/modules.R:37]: This this work for a module inside a module? (2x parents up the tree)

Comment (wch) [reply R/modules.R]: I updated to work with nested modules. I've also updated the test app.

File: R/modules.R [hunk 2]
```diff
@@ -31,11 +31,36 @@ createSessionProxy <- function(parentSession, ...) {
...
+  }
+
   stop("Attempted to assign value on session proxy.")
 }
 
 `[[<-.session_proxy` <- `$<-.session_proxy`
 
+# Given a session_proxy, search `parent` recursively to find the real
+# ShinySession object. If given a ShinySession, simply return it.
+find_ancestor_session <- function(x, depth = 5) {
```
Comment (schloerke) [inline R/modules.R:49]: Is there any way to know if there are more than 5 nested modules? I doubt it... but maybe we could raise it to 100 or something highly unlikely? (I think 5 is still obtainable. 100 is not.)

Comment (wch) [reply R/modules.R:49]: I'll raise it to 20.

**Review by schloerke — APPROVED** [review]
