### PR TITLE
fix(conditionalPanel): Coerce condition result to boolean

### LINKED ISSUE #4126: Infinite loop with `conditionalPanel`
### Example app

This app prints dots indefinitely:

```R
shinyApp(
  ui = div(
    id = "box",
    conditionalPanel(condition = "undefined"),
    tags$script(HTML("
      $('#box').on('hide', () => {
        Shiny.setInputValue('dot', Math.random());
      });
    "))
  ),
  server = function(input, output) {
    observeEvent(input$dot, cat("."))
  }
)
```

### Details

The  falsy condition in `conditionalPanel` causes it to trigger a `hide` event, upon which we update the `dot` input. This causes the condition to be evaluated again and another event to be fired, resulting in an endless loop.

It works because [this check](https://github.com/rstudio/shiny/blob/d84aa94762b4ffaf7533a007b6cb92c40f4f29af/srcts/src/shiny/shinyapp.ts#L620) ("Is the desired state different from the current state?") always evaluates to true if the condition passed to `conditionalPanel` is not a boolean. Replacing `undefined` with `42` and `hide` with `show` also results in an endless loop.

### Fix

My suggestion is to fix the problem by coercing the `condition` to a bool in [line 617](https://github.com/rstudio/shiny/blob/d84aa94762b4ffaf7533a007b6cb92c40f4f29af/srcts/src/shiny/shinyapp.ts#L617), like so:
```ts
const show = !!condFunc(nsScope);
```

A workaround for user code is to ensure that `condition` evaluates to a boolean (e.g. with `!!`).

### Notes

Checked with Shiny 1.9.1, but looking at git history the problem has been around for a while.

Perhaps this is not something many people will encounter, but in our case this bug was causing performance issues and it was very hard to find it (the `conditionalPanel()` and the event listener were pieces of two unrelated functionalities in a complex app).

### PR DESCRIPTION
**Pull request by gadenbuie**
Fixes #4126

The key fix here is to force the result of `condFunc()` to be boolean so that it can be correctly compared with the current state of the `conditionalPanel()`.

`condFunc()` is created by `scopeExprToFunc()` which was previously typed as returning a `boolean` value. In practice, however, this function returns an `unknown` value depending on the user expression. `scopeExprToFunc()` is sufficiently general to be useful in other places, so I relaxed the type from `boolean` to `unknown` (rather than doing the boolean coercion before returning). This also then gives a hint to users of `condFunc()` that they should verify the return value.

### CODE REVIEW

File: srcts/src/utils/index.ts [hunk 1]
```diff
@@ -178,7 +178,7 @@ function scopeExprToFunc(expr: string): (scope: unknown) => boolean {
     throw e;
   }
 
-  return function (scope: unknown): boolean {
+  return function (scope: unknown): unknown {
     return func.call(scope);
```
Comment (schloerke) [inline srcts/src/utils/index.ts:182]: Can we revert the type / `!!` changes and instead force a boolean here?

```suggestion
    return Boolean(func.call(scope));
```

Comment (schloerke) [reply srcts/src/utils/index.ts:182]: Hmmmm. But the name of the function doesn't point to bool.

Ok

File: srcts/src/shiny/shinyapp.ts [hunk 2]
```diff
@@ -614,7 +614,7 @@ class ShinyApp {
 
       const nsPrefix = el.attr("data-ns-prefix") as string;
       const nsScope = this._narrowScope(scope, nsPrefix);
-      const show = condFunc(nsScope);
+      const show = !!condFunc(nsScope);
```
Comment (schloerke) [inline srcts/src/shiny/shinyapp.ts:617]: I'd rather use the class instead of the accepted workaround of `!!`.

```suggestion
      const show = Boolean(condFunc(nsScope));
```

**Review by schloerke — APPROVED** [review]

File: srcts/src/shiny/shinyapp.ts (hunk 2 above)
Comment (gadenbuie) [reply srcts/src/shiny/shinyapp.ts]: Agreed, thanks!
