### PR TITLE
Fix dateInput when two-digit `yy` is used

### LINKED ISSUE #3197: When dateInput has format mm/dd/yy and has min and max, value is not set
This is from https://github.com/rstudio/shinycoreci-apps/issues/91.

Example app:

```R
start_date <- as.Date("2020-01-08")
shinyApp(
  fluidPage(
    dateInput('date', label = 'Date',
      value = start_date,
      min = start_date - 5,
      max = start_date + 5,
      format = "mm/dd/yy"
    ),
    verbatimTextOutput("txt", placeholder = TRUE)
  ),
  function(input, output) {
    output$txt <- renderPrint({
      input$date
    })
  }
)
```

This is what it looks like:
image

However, if the `format` is taken out, or if both `min` and `max` are removed, then the value shows up.

This behavior was introduced by #3038.

### PR DESCRIPTION
**Pull request by wch**
Closes #3197. It turns out this PR also fixes some other regressions. See test app in comment below.

### CODE REVIEW

**Comment by wch** [comment]
A test app for the many issues with the datepicker:

```R
library(shiny)
library(magrittr)
library(rlang)

# ==============================================================================
# date_yy module
# ==============================================================================
date_yy_ui <- function(id) {
  ns <- NS(id)
  start_date <- as.Date("2020-01-08")
  tagList(
    p("This should show 01/08/20 in the input field, and 2020-01-08 in the output.",
      "Issue ", a(href="https://github.com/rstudio/shiny/issues/3197", "#3197"), ",",
      "PR ", a(href="https://github.com/rstudio/shiny/pull/3201", "#3201")
    ),
    dateInput(ns('date'), label = 'Date',
      value = start_date,
      min = start_date - 5,
      max = start_date + 5,
      format = "mm/dd/yy"
    ),
    verbatimTextOutput(ns("txt"), placeholder = TRUE)
  )
}

date_yy_server <- function(id) {
  moduleServer(
    id,
    function(input, output, session) {
      output$txt <- renderPrint({
        input$date
      })
    }
  )
}

# ==============================================================================
# date_max module
# ==============================================================================
date_max_ui <- function(id) {
  ns <- NS(id)
  tagList(
    p("This should show current date in browser's time zone.",
      "Issue ", a(href="https://github.com/rstudio/shiny/issues/2335", "#2355")
    ),
    dateInput(ns("date"), "Date", max = Sys.Date()),
    verbatimTextOutput(ns("res"))
  )
}

date_max_server <- function(id) {
  moduleServer(
    id,
    function(input, output, session) {
      output$res <- renderPrint({
        input$date
      })
    }
  )
}


# ==============================================================================
# update_date module
# ==============================================================================
update_date_ui <- function(id) {
  ns <- NS(id)
  tagList(
    p("updateDateInput tests. When clicking the button below, the status should say OK each time, until i wraps around to 0.",
      "Issue ", a(href="https://github.com/rstudio/shiny/issues/2703", "#2703")
    ),
    dateInput(ns("date"), "Example", min = "2013-04-10", value = "2013-04-11", max = "2013-04-12"),
    actionButton(ns("go"), "Go"),
    verbatimTextOutput(ns("i_txt"))
  )
}

update_date_server <- function(id) {
  moduleServer(
    id,
    function(input, output, session) {
      # none <- character(0)
      dates <- list(
        list(min = 13,   value = NULL, max = NULL, expected = NULL, txt = "Set new min greater than old max"),
        list(min = 10,   value = 11,   max = 12  , expected = 11  , txt = "Reset"),
        list(min = 12,   value = NULL, max = NULL, expected = NULL, txt = "Set new min greater than old value"),
        list(min = 10,   value = 11,   max = 12  , expected = 11  , txt = "Reset"),

        list(min = NULL, value = NULL, max = 9   , expected = NULL, txt = "Set new max less than old min"),
        list(min = 10,   value = 11,   max = 12  , expected = 11  , txt = "Reset"),
        list(min = NULL, value = NULL, max = 10  , expected = NULL, txt = "Set new max less than old value"),
        list(min = 10,   value = 11,   max = 12  , expected = 11  , txt = "Reset"),

        list(min = 12,   value = 13,   max = 14  , expected = 13  , txt = "Set all going up, overlap"),
        list(min = 10,   value = 11,   max = 12  , expected = 11  , txt = "Reset"),
        list(min = 8,    value = 9,    max = 10  , expected = 9   , txt = "Set all going down, overlap"),
        list(min = 10,   value = 11,   max = 12  , expected = 11  , txt = "Reset"),

        list(min = 13,   value = 14,   max = 15  , expected = 14  , txt = "Set all going up, no overlap"),
        list(min = 10,   value = 11,   max = 12  , expected = 11  , txt = "Reset"),
        list(min = 7,    value = 8,    max = 9   , expected = 8   , txt = "Set all going down, no overlap"),
        list(min = 10,   value = 11,   max = 12  , expected = 11  , txt = "Reset")


        # # Note: The cases where it unsets min, max, or value have yet to be
        # # implemented, so they're commented out for now.
        # list(min = none, value = NULL, max = NULL, txt = "Unset min"),
        # list(min = 10,   value = 11,   max = 12  , txt = "Reset"),
        # list(min = NULL, value = NULL, max = none, txt = "Unset max"),
        # list(min = 10,   value = 11,   max = 12  , txt = "Reset"),
        # list(min = NULL, value = none, max = NULL, txt = "Unset value"),
        # list(min = 10,   value = 11,   max = 12  , txt = "Reset")
      )

      dates <- lapply(dates, function(row) {
        lapply(row, function(val) {
          if (is.character(val))  val
          else if (!is.null(val)) sprintf("2013-04-%02d", val)
          else                    NULL
        })
      })

      i <- reactiveVal(0)
      observe({
        i(i() + 1)
        if (i() > length(dates)) {
          i(1)
        }

        updateDateInput(session, "date",
          min   = dates[[i()]]$min,
          value = dates[[i()]]$value,
          max   = dates[[i()]]$max
        )
      }) %>%
        bindEvent(input$go)

      output$i_txt <- renderText({
        n <- i()
        if (i() == 0) {
          action   <- ""
          expected <- ""
          status   <- "OK"
        } else {
          action   <- dates[[i()]]$txt
          expected <- as.Date(dates[[i()]]$expected)
          status   <- if (identical(input$date, expected)) "OK" else "Error"
        }
        paste0(
          "i = ", i(),
          "\nAction:     ", action,
          "\ninput$date: ", input$date,
          "\nexpected:   ", expected,
          "\nstatus:     ", status
        )
      }) %>%
        bindEvent(input$date)
    }
  )
}


# ==============================================================================
# update_date_range module
# ==============================================================================
update_date_range_ui <- function(id) {
  ns <- NS(id)
  tagList(
    p("updateDateRangeInput tests. ",
      "When moving the slider, the start and end values should be the number -1 and +1, ",
      "and the min and possible values should be the number -5 and + 5.",
      "Issue ", a(href="https://github.com/rstudio/shiny/issues/2703", "#2703")
    ),
    sliderInput(ns("n"), "Day of month", 1, 30, 10),
    dateRangeInput(ns("inDateRange"), "Input date range")
  )
}

update_date_range_server <- function(id) {
  moduleServer(
    id,
    function(input, output, session) {
      observe({
        date <- as.Date(paste0("2013-04-", input$n))

        updateDateRangeInput(session, "inDateRange",
          label = paste("Date range label", input$n),
          start = date - 1,
          end = date + 1,
          min = date - 5,
          max = date + 5
        )
      })

    }
  )
}


ui <- fluidPage(
  "Note: It is helpful to run these tests when the date in client's time zone is different from ",
  "the date in UTC. One way to do this is (for example) to set the computer's time zone to US Central Time",
  "and set the clock to 8:00 PM.",
  hr(),
  date_yy_ui("date_yy"),
  hr(),
  date_max_ui("date_max"),
  hr(),
  update_date_ui("update_date"),
  hr(),
  update_date_range_ui("update_date_range")
)
server <- function(input, output, session) {
  date_yy_server("date_yy")
  date_max_server("date_max")
  update_date_server("update_date")
  update_date_range_server("update_date_range")
}

shinyApp(ui, server)
```

File: srcjs/input_binding_date.js [hunk 1]
```diff
@@ -212,7 +217,14 @@ $.extend(dateInputBinding, {
     if (isNaN(d))
       return null;
 
-    return new Date(d.getTime());
+    return d;
+  },
+  // A Date can have any time during a day; this will return a new Date object
+  // set to 00:00 in UTC.
+  _normalizeDate: function(date) {
```
Comment (cpsievert) [inline srcjs/input_binding_date.js:224]: Maybe `_roundDate` would be better name (normalize could be referring to timezone)?

**Review by cpsievert — APPROVED** [review]
Awesome, thank you! 👍
