### PR TITLE
Resolves #1933: Serve-side selectize extended to all inputs

### LINKED ISSUE #1933: Server-side selectize doesn't work for some types of inputs
When server-side selectize is used, there are some types of inputs that don't work. They are illustrated by the test app at https://github.com/rstudio/shiny/pull/1861#issuecomment-337296766.

### PR DESCRIPTION
**Pull request by tmastny**
Resolves #1933.

Reproducible Example:
```
library(shiny)
bigvec <- paste0("a", 1:1e5)
named_bigvec <- setNames(bigvec, bigvec)
nested_biglist <- lapply(named_bigvec, function(item) setNames(list(item), item))

test_set <- list(
  "Unnamed vector" = c(1, 2),
  "Named vector" = c(a = 1, B = 2),
  "Partially named vector" = c(a = 1, B = 2, 3),
  "Unnamed list" = list(1, 2),
  "Named list" = list(a = 1, B = 2, c = 3),
  "Partially named list" = list(a = 1, B = 2, 3),
  "Nested list" = list(a = 1, B = list(B = 2, C = 4, 5), c = list(3)),
  "Big unnamed vector (server-side only)" = bigvec,
  "Big named vector (server-side only)" = named_bigvec,
  "Big unnamed list (server-side only)" = as.list(bigvec),
  "Big named list (server-side only)" = as.list(named_bigvec),
  "Big nested list (server-side only)" = nested_biglist
)

ui <- fluidPage(
  sidebarPanel(
    checkboxInput("server", "Server-side selectize"),
    selectInput("set", "Test set", names(test_set)),
    selectizeInput("select", "Select", choices = NULL)
  ),
  mainPanel(
    verbatimTextOutput("txt")
  )
)

server <- function(input, output, session) {
  validateSelection <- function() {
    if (is.null(input$set) || is.null(input$server))
      return(FALSE)
    if (!input$server && grepl("server-side", input$set))
      return(FALSE)

    TRUE
  }

  observe({
    if (!validateSelection()) return()
    cat("starting updateSelectizeInput... ")
    updateSelectizeInput(
      session,
      "select",
      choices = test_set[[input$set]],
      selected = NULL,
      server = input$server
    )
    cat("done\n")
  })

  output$txt = renderPrint({
    if (!validateSelection())
      return("This test set must be used with server-side selectize (too slow otherwise)")
    input$select
  })
}

# Launch app with external browser because RStudio's built-in browser might
# not be as fast.
runApp(shinyApp(ui, server), launch.browser = T, port=9000)
```

### CODE REVIEW

File: srcjs/input_binding_select.js [hunk 1]
```diff
@@ -55,9 +55,11 @@ $.extend(selectInputBinding, {
     if (data.hasOwnProperty('url')) {
       selectize = this._selectize(el);
       selectize.clearOptions();
+      selectize.clearOptionGroups();
       var thiz = this, loaded = false;
```
Comment (wch) [inline srcjs/input_binding_select.js]: I know you didn't do this, but can you change `thiz` to `self`?

File: srcjs/input_binding_select.js [hunk 2]
```diff
@@ -55,9 +55,11 @@ $.extend(selectInputBinding, {
...
       selectize.settings.load = function(query, callback) {
         var settings = selectize.settings;
+        var thiz2 = this;
```
Comment (wch) [inline srcjs/input_binding_select.js]: Is `thiz2` really necessary?

File: srcjs/input_binding_select.js [hunk 3]
```diff
@@ -111,7 +120,10 @@ $.extend(selectInputBinding, {
     var options = $.extend({
       labelField: 'label',
       valueField: 'value',
-      searchField: ['label']
+      searchField: ['label'],
+      optgroupField: 'group',
+			optgroupLabelField: 'group',
```
Comment (wch) [inline srcjs/input_binding_select.js]: Indentation: no tabs!

File: R/update-input.R [hunk 4]
```diff
@@ -660,7 +668,46 @@ updateSelectizeInput <- function(session, inputId, label = NULL, choices = NULL,
...
+      list(
+        label = lab,
+        value = as.character(choice),
+        group = group
+      )
+    }, SIMPLIFY = FALSE)
+
+
+    extract_vector <- function(x, name) {
+      vecs <- lapply(x, `[[`, name)
```
Comment (wch) [inline R/update-input.R]: The existing implementation of `extract_vector ` was written to work when each list contained vectors of length >= 1. But if it's known that length == 1, and if the type is known ahead of time, then this could be replaced with `vapply`, and the `do.call` won't be necessary. (I think that the vectors are all char vectors, right?)

Comment (wch) [reply R/update-input.R]: Actually, never mind what I said. If I'm reading the code correctly now, the lists contained in `choice_list` can have variable length, in which case you need the existing `lapply` version.

Comment (tmastny) [reply R/update-input.R]: Yes, each list can contain vectors of length >= 1. For example, if `choices <- list(a = 1, B = list(B = 2, C = 4, 5), c = list(3))` then `choice_list` equals:
```
$a
$a$label
[1] "a"

$a$value
[1] "1"

$a$group
[1] ""


$B
$B$label
[1] "B" "C" "5"

$B$value
[1] "2" "4" "5"

$B$group
[1] "B" "B" "B"


$c
$c$label
[1] "3"

$c$value
[1] "3"

$c$group
[1] "c"
```
However, the vectors are all character vectors.

File: srcjs/input_binding_select.js (hunk 2 above)
Comment (tmastny) [reply srcjs/input_binding_select.js]: Good catch. In fact, I can get rid of all of "thiz."

Comment (wch) [reply srcjs/input_binding_select.js]: I haven't looked at it closely yet, but you might still need `thiz`/`self`. (I'm assuming `thiz` was there for a reason.) You may already know this, but `this` in Javascript doesn't behave the way that it does in other languages.

For example, see https://gist.github.com/wch/b6ae0c7d88285f49c6b328c39f61e8da

Comment (tmastny) [reply srcjs/input_binding_select.js]: It looked like the original `thiz` was referring to the binding object, and was calling the `setValue` method. `thiz2` was referring to the selectize object (as per [this example](https://github.com/selectize/selectize.js/issues/151#issuecomment-111056161)) and was calling the `setValue` selectize method. 

However, in all cases I believe `thiz` was unnecessary as we could explicitly use the `selectize` variable declared on line 56.

**Comment by tmastny** [comment]
For QA: I've created an app and shinytest file that iterates through selectize functionality: 
https://github.com/rstudio/shiny-examples/tree/selectize-server/135-selectize-server

`mytest-expected` in the `tests` directory was ran on my fork of Shiny. You can verify that the existing selectize functionality still works by running that test on the master branch. All tests with the `Server-side selectize` checkbox unchecked should pass on the master branch. 

The functionality tested includes
   - testing `selected = NULL` in `updateSelectizeInput` behaves as expected on the server-side.
      - the `selected` parameter has different behavior for single vs. multiple selectize, see `updateSelectizeInput` docs.
   - testing server-side selectize works with both single and multiple selectize by using the `multiple` parameter in `selectizeInput`
   - testing server-side selectize works on lists and builds optgroups

File: R/update-input.R [hunk 5]
```diff
@@ -643,10 +643,18 @@ updateSelectizeInput <- function(session, inputId, label = NULL, choices = NULL,
     return(updateSelectInput(session, inputId, label, choices, selected))
   }
 
+  noOptGroup <- TRUE
+  for (i in 1:length(choices)) {
```
Comment (wch) [inline R/update-input.R]: Should use `seq_along` here.

File: R/update-input.R [hunk 6]
```diff
@@ -643,10 +643,18 @@ updateSelectizeInput <- function(session, inputId, label = NULL, choices = NULL,
...
+    if (is.list(choices[[i]])) {
```
Comment (wch) [inline R/update-input.R]: Should also check for char vectors of length > 1. (?)

File: R/update-input.R [hunk 7]
```diff
@@ -643,10 +643,18 @@ updateSelectizeInput <- function(session, inputId, label = NULL, choices = NULL,
...
+      noOptGroup <- FALSE
+      break()
+    }
+  }
+
   # convert a single vector to a data frame so it returns {label: , value: }
-  # other objects return arbitrary JSON {x: , y: , foo: , ...}
-  choices <- if (is.atomic(choices)) {
+  choices <- if (is.atomic(choices) || noOptGroup) {
```
Comment (wch) [inline R/update-input.R]: If `choices` is atomic, then we can skip the `noOptGroup` loop above.

File: R/update-input.R [hunk 8]
```diff
@@ -643,10 +643,18 @@ updateSelectizeInput <- function(session, inputId, label = NULL, choices = NULL,
...
     # fast path
+    if (is.list(choices)) choices <- unlist(choices)
```
Comment (wch) [inline R/update-input.R]: Maybe add a comment that if it got here, it must be a flat list.

File: R/update-input.R [hunk 9]
```diff
@@ -660,7 +668,46 @@ updateSelectizeInput <- function(session, inputId, label = NULL, choices = NULL,
     data.frame(label = lab, value = choices, stringsAsFactors = FALSE)
   } else {
     # slow path
-    as.data.frame(choices, stringsAsFactors = FALSE)
+    list_names <- names(choices)
+    if (is.null(list_names)) list_names <- ""
```
Comment (wch) [inline R/update-input.R]: Use `rep()` here instead of recycling, for clarity.

File: srcjs/input_binding_select.js [hunk 10]
```diff
@@ -84,9 +85,17 @@ $.extend(selectInputBinding, {
             callback();
           },
           success: function(res) {
```
Comment (wch) [inline srcjs/input_binding_select.js]: Can you add a comment that shows an example the structure of `res`?

Comment (wch) [reply srcjs/input_binding_select.js]: Can you explain that `success` is called after the options are added, but before the groups, and that groups need to be added manually?
