### PR TITLE
Address r-devel's change in `is.atomic(NULL)` behavior

### LINKED ISSUE #3906: `is.atomic(NULL)` results in test errors on R-devel
`is.atomic(NULL)` results in test errors on R-devel, and CRAN wants a new version of Shiny by Oct 14.

From https://cran.r-project.org/web/checks/check_results_shiny.html

image

```
checking tests ... [42s/70s] ERROR
  Running ‘testthat.R’ [42s/69s]
Running the tests in ‘tests/testthat.R’ failed.
Complete output:
  > library(testthat)
  > library(shiny)
  >
  > test_check("shiny")
  [ FAIL 4 | WARN 0 | SKIP 14 | PASS 1573 ]
  
  ══ Skipped tests (14) ══════════════════════════════════════════════════════════
  • File system is not case-sensitive (1): 'test-app.R:32:3'
  • I'm not sure of a great way to test this without timers. (1):
    'test-test-server.R:218:3'
  • Not testing in CI (1): 'test-devmode.R:17:3'
  • On CRAN (10): 'test-pkgdown.R:3:3', 'test-reactivity.r:147:3',
    'test-reactivity.r:1239:3', 'test-reactivity.r:1318:3',
    'test-stacks.R:127:3', 'test-tabPanel.R:51:3', 'test-tabPanel.R:65:3',
    'test-tabPanel.R:72:3', 'test-tabPanel.R:87:3', 'test-utils.R:177:3'
  • shinytest2 cannot be loaded (1): 'test-test-shinyAppTemplate.R:2:1'
  
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure ('test-utils.R:79:3'): need() works as expected ─────────────────────
  need(NULL, FALSE) is not FALSE
  
  `actual` is NULL
  `expected` is a logical vector (FALSE)
  ── Failure ('test-utils.R:118:3'): req works ───────────────────────────────────
  `req(NULL, value <- 1)` did not throw the expected error.
  ── Failure ('test-utils.R:119:3'): req works ───────────────────────────────────
  `value` (`actual`) not equal to 0 (`expected`).
  
    `actual`: 1
  `expected`: 0
  ── Failure ('test-utils.R:135:3'): req works ───────────────────────────────────
  `do.call(req, c(as.list(1:1000), list(NULL)))` did not throw the expected error.
  
  [ FAIL 4 | WARN 0 | SKIP 14 | PASS 1573 ]
  Error: Test failures
  Execution halted
```

### PR DESCRIPTION
**Pull request by cpsievert**
Closes #3906

### CODE REVIEW

File: tests/testthat/test-tabPanel.R [hunk 1]
```diff
@@ -18,6 +18,9 @@ expect_snapshot2 <- function(...) {
   if (getRversion() < "3.6.0") {
     skip("Skipping snapshots on R < 3.6 because of different RNG method")
   }
+  if (packageVersion("htmltools") <= "0.5.6") {
+    skip("Skipping snapshots since htmltools is 'outdated'")
+  }
```
Comment (cpsievert) [inline tests/testthat/test-tabPanel.R:23]: This is needed since these `tabPanel()` tests ultimately call `tagQuery()` in such a way that https://github.com/rstudio/htmltools/pull/408 becomes problematic (for r-devel).

File: tests/testthat/test-tabPanel.R [hunk 2]
```diff
@@ -18,6 +18,9 @@ expect_snapshot2 <- function(...) {
   if (getRversion() < "3.6.0") {
     skip("Skipping snapshots on R < 3.6 because of different RNG method")
   }
+  if (packageVersion("htmltools") <= "0.5.6") {
```
Comment (cpsievert) [inline tests/testthat/test-tabPanel.R:21]:
```suggestion
  if (packageVersion("htmltools") <= "0.5.6" && getRversion() > "4.3.1") {
```

**Review by gadenbuie — APPROVED** [review]
