### PR TITLE
fix: Allow `bindInputs()` to no-op when attempting to bind currently bound inputs

### LINKED ISSUE #3943: Client error console prevents apps with matching input and output IDs
#3931 adds a check for matching input IDs that match output IDs, which was previously allowed. The following app runs with shiny 1.8.0 and will break in the 1.8.0.9000 because of the duplicate `caption` ID, which is used once for an input and once for an output.

```r
library(shiny)

ui <- fluidPage(
  selectInput("caption", "Caption", "Data Summary"),
  textOutput("caption")
)

server <- function(input, output, session) {
  output$caption <- renderText(input$caption)
}

shinyApp(ui, server)
```

The following ID was repeated: "caption": 1 input and 1 output

This example is extracted from [shinycoreci: 003-reactivity](https://github.com/rstudio/shinycoreci/blob/main/inst/apps/003-reactivity/app.R).

We may want to reduce the severity of the message to a warning in the case of `1 input and 1 output`, or we may want to remove this particular check altogether.

Personally, I think it's important that we continue to support overlapping IDs in input and outputs, e.g. `input$caption` and `output$caption`.

### LINKED ISSUE #3944: Client error console and inserted/removed UI elements
With #3931, when dynamically adding UI to a running app, it seems that the matching IDs checks run on the entire app and flag stable input/output elements as duplicated.

The following app ([shinycoreci: 111-insert-ui](https://github.com/rstudio/shinycoreci/blob/main/inst/apps/111-insert-ui/)) reproduces the problem:

```r
library(shiny)

ui <- fluidPage(
  actionButton('insertBtn', 'Insert'),
  actionButton('removeBtn', 'Remove'),
  tags$div(id = 'placeholder') #<< ui elements will be added here
)

server <- function(input, output) {

  ## keep track of elements inserted and not yet removed
  inserted <- c()

  observeEvent(input$insertBtn, {
    count <- input$insertBtn
    # give the inserted element a unique id so we can remove it later
    id <- paste0('txt', count)
    
    # push a new element in to the app
    insertUI(
      selector = '#placeholder',
      ui = tags$div(
        tags$p(paste('Element number', count)),
        id = id
      )
    )
    inserted <<- c(inserted, id)
  })

  observeEvent(input$removeBtn, {
    # pop last inserted element out of the app
    removeUI(
      selector = paste0('#', inserted[length(inserted)])
    )
    # and remove it from the list of inserted elements
    inserted <<- inserted[-length(inserted)]
  })

}

shinyApp(ui, server)

```

## With client error console

https://github.com/rstudio/shiny/assets/5420529/3655c873-ec1e-4115-b5f9-3adf129fd7ee

## shiny 1.8.0

https://github.com/rstudio/shiny/assets/5420529/4b1472be-6443-41da-9a5d-1c591904a1c3

### LINKED ISSUE #3945: Client error console issue with dynamic bslib accordions
I'm opening this here to triage, this is most likely another variant of #3944, or it could be another issue entirely.

**Steps to reproduce:**

1. Run [306-accordion-add-remove](https://github.com/rstudio/shinycoreci/blob/fix-snaps-2023-11-28/inst/apps/306-accordion-add-remove/app.R) from shinycoreci
2. Remove one letter from the "Displayed sections" panel, e.g. remove `B`.
3. Add the removed panel back.
4. Click the checkbox "Allow multiple panels to be open" to deselect the setting.
5. Observe the client error console: _The following ID was repeated: "acc": 2 inputs_

https://github.com/rstudio/shiny/assets/5420529/5a978112-3c84-4df4-befc-03feb7ac6959

What's interesting is that adding the panel calls `accordion_panel_insert()`. Without this (e.g. if you skip step 3) the client error isn't displayed. Moreover, this error isn't shown when the `accordion_panel_insert()` happens, it's shown when `input$multiple` is toggled (step 4), which calls `renderUI()` to create an entirely new `accordion(id = "acc")`.

Also, if you repeat steps 2 and 3 `n` times before toggling `input$multiple`, the client error will report `n + 1` repeated `"acc"` input IDs.

### PR DESCRIPTION
**Pull request by gadenbuie**
Fixes #3943
Fixes #3944
Fixes #3945

Prior to #3931, `bindInputs()` could be called more than once on the same input element and only the first binding would be applied. This behavior was changed in https://github.com/rstudio/shiny/commit/62eb485e1c138746d920fa8df9b6ef59e96b2243

This PR makes a few changes to the implementation in #3931, plus one change to improve `bindInputs()` from the previous status quo:

1. `bindInputs()` once again no-ops if an attempt is made to bind to a currently bound input. Prior to #3931, we had a light-weight input binding registry and we would look to see if `id` was marked as bound, and no-op if it was in the registry. With #3931, we always re-bind the input element regardless of its binding status, most likely assuming that `bindAll()` was paired with a prior unbinding step at the right scope. This doesn't always play out in practice.

   With this PR, we now inspect the element directly. If it has the input binding data value that signifies it's currently bound, we do nothing -- after we make sure the element is included in the `bindingsRegistry`. (Inspecting the element directly is also what `bindOutputs()` does, so this bring `bindInputs()` in line with that function.)

2. For both the binding of inputs and outputs, I relocated the `bindingsRegistry.addBinding()` call to happen _after_ Shiny performs the binding and before it announces the binding to the rest of the world via the `shiny:bound` event. There were a few places where we could unintentionally count a new binding when no actual binding was taking place.

3. I've updated the `bindingsRegistry.checkValidity()` method to only throw when an individual binding type has more than one binding. The lets `input$caption` and `output$caption` work as before, but if a second `output$caption` were added, the client error console will report all bindings and alert users. In the future we could update the error console to also handle warnings (so maybe we should call this the Shiny client message console?)

4. There are also a few additional miscellaneous fixes, the most salient of which is fixing the spelling of "registery" to "registry".

---

I've checked all of the shinycoreci apps affected by the error console (listed in https://github.com/rstudio/shinycoreci/pull/248) and they all work as expected with the changes in this PR.

### CODE REVIEW

File: srcts/src/shiny/bind.ts [hunk 1]
```diff
@@ -204,10 +223,17 @@ function bindInputs(
       if (el.hasAttribute("data-shiny-no-bind-input")) continue;
       const id = binding.getId(el);
 
-      // Check if ID is falsy, skip
+      // Don't bind if ID is falsy...
       if (!id) continue;
 
-      bindingsRegistery.addBinding(id, "input");
+      // ...or if this element is already registered with a binding
+      if ($(el).data("shiny-input-binding")) {
```
Comment (jcheng5) [inline srcts/src/shiny/bind.ts:230]: I think `el.classList.contains("shiny-bound-input")` is a better test. If I'm reading this correctly, `.shiny-bound-input` directly reflects whether this exact element is bound or not; whereas `$(el).data("shiny-input-binding")` will be truthy if this element has _ever_ been bound.

File: srcts/src/shiny/bind.ts [hunk 2]
```diff
@@ -204,10 +223,17 @@ function bindInputs(
       if (el.hasAttribute("data-shiny-no-bind-input")) continue;
       const id = binding.getId(el);
 
-      // Check if ID is falsy, skip
+      // Don't bind if ID is falsy...
       if (!id) continue;
 
-      bindingsRegistery.addBinding(id, "input");
```
Comment (gadenbuie) [inline srcts/src/shiny/bind.ts:210]: The change here would cause currently-bound inputs to both rebind and to increment the binding registry count, unless an intervening `unbindAll()` happened in between.

Which ultimately would conflate binding the same binding to the same element (it's already bound so the binding should no-op) with binding a _new element_ with the same ID.

File: srcts/src/shiny/bind.ts (hunk 1 above)
Comment (jcheng5) [reply srcts/src/shiny/bind.ts:230]: And if you replace that test then you can simply `continue` without needing to conditionally call `bindingsRegistry.addBinding(id, "input")`.

File: srcts/src/shiny/bind.ts [hunk 3]
```diff
@@ -61,31 +61,49 @@ const bindingsRegistery = (() => {
...
-   * @returns ShinyClientError if current ID bindings are invalid, otherwise null
+   * @returns ShinyClientError if current ID bindings are invalid, otherwise
+   * returns an ok status.
    */
   function checkValidity():
     | { status: "error"; error: ShinyClientError }
     | { status: "ok" } {
-    const duplicateIds: IdToBindingTypes = new Map();
+    const duplicateIds: { [id: string]: { input: number; output: number } } =
+      {};
```
Comment (nstrayer) [inline srcts/src/shiny/bind.ts:73]: Curious as to why we're switching away from `Map` here? Maps tend to be the best choice for collections of unknown sizes.

File: srcts/src/shiny/bind.ts [hunk 4]
```diff
@@ -279,8 +306,6 @@ async function bindOutputs(
       // Check if ID is falsy
       if (!id) continue;
 
-      bindingsRegistery.addBinding(id, "output");
-
```
Comment (gadenbuie) [inline srcts/src/shiny/bind.ts:283]: There are a few conditions in the lines below (not seen in the diff) where we would `continue` and not bind to `el` because it's already bound. If we add this `id` to the `bindingsRegistry` here, then we'll overcount the bindings on `id`.

File: srcts/src/shiny/bind.ts (hunk 1 above)
Comment (gadenbuie) [reply srcts/src/shiny/bind.ts:230]: Yeah I went this way because I knew it'd induce conversation about which approach is better. 

`unbindOutputs()` should remove both the class and the data, so the presence of either should in theory be a solid signal. I'm inclined to lean toward the data value, since it's less likely a user would have included `data-shiny-input-binding` in the markup (but maybe they've added `.shiny-bound-input` to the class list for some reason?). If we really really want to be certain we could test the value of `$(el).data("shiny-input-binding")` but that seems excessive.

https://github.com/rstudio/shiny/blob/3e00632052b1401eb31c220c7f03c7da619b69ff/error-console-insert-ui/srcts/src/shiny/bind.ts#L404-L405

Comment (gadenbuie) [reply srcts/src/shiny/bind.ts:230]: Oh wait! Yes `unbindInputs()` leaves the data attribute in tact. So there is a currently correct answer of testing the class

File: srcts/src/shiny/bind.ts [hunk 5]
```diff
@@ -204,10 +223,17 @@ function bindInputs(
...
-      // Check if ID is falsy, skip
+      // Don't bind if ID is falsy...
       if (!id) continue;
 
-      bindingsRegistery.addBinding(id, "input");
+      // ...or if this element is already registered with a binding
+      if ($(el).data("shiny-input-binding")) {
+        if (!bindingsRegistry.isRegistered(id, "input")) {
+          bindingsRegistry.addBinding(id, "input");
+        }
```
Comment (nstrayer) [inline srcts/src/shiny/bind.ts]: As this is the only use of this method and it immediately follows logic involving the registry itself, I think it should be kept internal and added to the logic of `addBinding()` in order to keep the exposure to the surface of the registry implementation as small as possible.

File: srcts/src/shiny/bind.ts [hunk 6]
```diff
@@ -151,6 +169,7 @@ const bindingsRegistery = (() => {
   }
 
   return {
+    isRegistered,
```
Comment (nstrayer) [inline srcts/src/shiny/bind.ts]: Probably shouldn't be exported to minimize the surface area of the registry object. See the below comment for more context.

File: srcts/src/shiny/bind.ts (hunk 1 above)
Comment (gadenbuie) [reply srcts/src/shiny/bind.ts]: I updated `bindInputs()` to check the class in 26e51092c3a33c070df728ef86847053a7e3f606 and then removed the `.isRegistered()` method from `bindingsRegistry` since it isn't used anywhere else in b67b0623e9f8cb65175a89a369f2191e6779b838.

File: srcts/src/shiny/bind.ts [hunk 7]
```diff
@@ -102,44 +120,44 @@ const bindingsRegistery = (() => {
...
    * @param id Id to add
-   * @param inputOrOutput Whether the id is for an input or output binding
+   * @param type Binding type, either "input" or "output"
    */
-  function addBinding(id: string, inputOrOutput: "input" | "output"): void {
+  function addBinding(id: string, type: "input" | "output"): void {
     if (id === "") {
       throw new ShinyClientError({
-        headline: `Empty ${inputOrOutput} ID found`,
+        headline: `Empty ${type} ID found`,
```
Comment (nstrayer) [inline srcts/src/shiny/bind.ts:120]: I'm biased, but I think the more descriptive parameter/variable name is nice here as it's self-documenting and when using it you don't need to reference the typescript types to understand the possible values. If we think we may add more binding types in the future I could see making it more genericly `type`, however.

File: srcts/src/shiny/bind.ts (hunk 5 above)
Comment (gadenbuie) [reply srcts/src/shiny/bind.ts]: thanks, yeah I took this out in b67b0623e9f8cb65175a89a369f2191e6779b838

File: srcts/src/shiny/bind.ts [hunk 8]
```diff
@@ -61,31 +61,32 @@ const bindingsRegistery = (() => {
...
+      {};
 
-    bindings.forEach((inputOrOutput, id) => {
-      if (inputOrOutput.length > 1) {
-        duplicateIds.set(id, inputOrOutput);
+    // count duplicate IDs of each binding type
+    bindings.forEach((idTypes, id) => {
+      const nInputs = idTypes.filter((s) => s === "input").length;
+      const nOutputs = idTypes.filter((s) => s === "output").length;
+
```
Comment (nstrayer) [inline srcts/src/shiny/bind.ts:79]:
```suggestion
      const nInputs = idTypes.filter((bindingType) => bindingType === "input").length;
      const nOutputs = idTypes.filter((bindingType) => bindingType === "output").length;

```

File: srcts/src/shiny/bind.ts (hunk 3 above)
Comment (gadenbuie) [reply srcts/src/shiny/bind.ts]: I switched it back to a map in 616bda08bc823b95e37e6afc53545008a34a3ae6

File: srcts/src/shiny/bind.ts [hunk 9]
```diff
@@ -61,31 +61,32 @@ const bindingsRegistery = (() => {
...
+      if (nInputs > 1 || nOutputs > 1) {
+        duplicateIds[id] = { input: nInputs, output: nOutputs };
       }
```
Comment (nstrayer) [inline srcts/src/shiny/bind.ts]: Is this the only bit of logic that's different here? If it is I may advocate for reducing changes to just this to keep changes focused. The new code feels a bit harder to follow (although that's probably because I wrote the original.)

File: srcts/src/shiny/bind.ts (hunk 7 above)
Comment (gadenbuie) [reply srcts/src/shiny/bind.ts:119]: I switched it to `type` because `isRegistered()` would take `inputOrOutput: "all" | "input" | "output"`, which wasn't just input or output. I personally found `inputOrOutput` to be slightly confusing -- given the longer name it feels like there's something more going on with it. I don't have strong feelings and could easily revert it for a smaller diff.

File: srcts/src/shiny/bind.ts (hunk 9 above)
Comment (gadenbuie) [reply srcts/src/shiny/bind.ts]: Sort of, but we also have to count the number of each type earlier. Before you would add an `id` to `duplicateIds` if `bindings.get(id).length > 1` but we need this logic to happen earlier so we can take into account whether there are more than one of the same type as the inclusion criteria.

File: srcts/src/shiny/bind.ts (hunk 7 above)
Comment (gadenbuie) [reply srcts/src/shiny/bind.ts:119]: Given the change suggested here, I'd advocate for `bindingType` instead of `inputOrOutput`. Then `bindingType` is used everywhere to mean the same thing.

Comment (gadenbuie) [reply srcts/src/shiny/bind.ts]: Refactored in b124d1b95e8d4309d6f6526e3592c69b5c5da6fe

File: srcts/src/shiny/bind.ts [hunk 10]
```diff
@@ -9,6 +9,7 @@ import type {
 import { shinyAppBindOutput, shinyAppUnbindOutput } from "./initedMethods";
 import { sendImageSizeFns } from "./sendImageSize";
 import { ShinyClientError } from "./error";
+import { types } from "util";
```
Comment (nstrayer) [inline srcts/src/shiny/bind.ts:12]: Spurious vscode auto-complete import

File: srcts/src/shiny/bind.ts [hunk 11]
```diff
@@ -47,45 +48,54 @@ function valueChangeCallback(
...
-   * @returns ShinyClientError if current ID bindings are invalid, otherwise null
+   * @returns ShinyClientError if current ID bindings are invalid, otherwise
+   * returns an ok status.
    */
   function checkValidity():
     | { status: "error"; error: ShinyClientError }
     | { status: "ok" } {
-    const duplicateIds: IdToBindingTypes = new Map();
+    const duplicateIds: Map<string, { input: number; output: number }> =
+      new Map();
```
Comment (nstrayer) [inline srcts/src/shiny/bind.ts:76]:
```suggestion
    const duplicateIds = newMap<string, Record<BindingTypes, number>>();
```

File: srcts/src/shiny/bind.ts [hunk 12]
```diff
@@ -47,45 +48,54 @@ function valueChangeCallback(
...
+
+    const countBindingType = (
+      types: BindingTypes[],
+      bindingType: BindingTypes
+    ) => {
+      return types.filter((type) => type === bindingType).length;
+    };
```
Comment (nstrayer) [inline srcts/src/shiny/bind.ts:83]:
```suggestion
    type BindingCounts = { [T in BindingTypes]: number };
    const duplicateIds = new Map<string, BindingCounts>();

```

File: srcts/src/shiny/bind.ts [hunk 13]
```diff
@@ -47,45 +48,54 @@ function valueChangeCallback(
...
-        duplicateIds.set(id, inputOrOutput);
+    // count duplicate IDs of each binding type
+    bindings.forEach((idTypes, id) => {
+      const nInputs = countBindingType(idTypes, "input");
+      const nOutputs = countBindingType(idTypes, "output");
+
+      if (nInputs > 1 || nOutputs > 1) {
+        duplicateIds.set(id, { input: nInputs, output: nOutputs });
       }
     });
```
Comment (nstrayer) [inline srcts/src/shiny/bind.ts:93]:
```suggestion
    // count duplicate IDs of each binding type
    bindings.forEach((idTypes, id) => {
      const counts: { [T in BindingTypes]: number } = { input: 0, output: 0 };

      idTypes.forEach((type) => (counts[type] += 1));

      if (counts.input > 1 || counts.output > 1) {
        duplicateIds.set(id, counts);
      }
    });
```

File: srcts/src/shiny/bind.ts (hunk 7 above)
Comment (nstrayer) [reply srcts/src/shiny/bind.ts]: Oh `BindingType` and then ensuring consistency is better!

File: srcts/src/shiny/bind.ts (hunk 13 above)
Comment (nstrayer) [reply srcts/src/shiny/bind.ts:93]: Just a couple of suggestions for avoiding an extra abstraction and also keeping nice type checking with the new `BindingTypes` type.

Comment (nstrayer) [reply srcts/src/shiny/bind.ts:93]: I'm much more attached to the comment explaining the somewhat perplexing-out-of-context `if` statement than anything here though.

File: srcts/src/shiny/bind.ts (hunk 12 above)
Comment (gadenbuie) [reply srcts/src/shiny/bind.ts]: Thanks, that is a nice way to have everything flow through the `BindingTypes` type!

File: srcts/src/shiny/bind.ts (hunk 13 above)
Comment (gadenbuie) [reply srcts/src/shiny/bind.ts]: I rewrote the logic to check if any count is `> 1`, not just input and output counts. I think the code itself is clear enough, but I agree we need to record the relevant parts of this discussion. I added that into the jsdoc so that it's close to the code and also shows up in the hover cards. (688334402d68e5f88e4d6f980cacc9b03da8dc75)

And to clarify, I think we _do_ want to allow duplicate IDs across inputs and outputs; what we don't want to do is to have more than one element on the page with the same `id`. In other words: users shouldn't have to think of inputs and outputs as a shared namespace. I think the onus is us as the framework authors to make the markup work.

**Comment by nstrayer** [comment]
I'm mostly good with this. 
The one part I'm uneasy about is the explicit encoding of the acceptability of a matching id _if_ it's just a single input and output. I get that we need to not break legacy apps, but I fear that by hard coding into the logic here and not having an active strategy to fix it, or message about it being non-ideal, we've just codified bad accessibility/dev practices into the codebase. At least previously it was just a bug that we allowed it. 

Part of the purpose of the console was to surface these exact types of long-standing bugs. Maybe we should not ignore the case but add it as a non-`throw`ing warning. I'd be curious about @jcheng5 and @wch's opinions about this.

**Comment by gadenbuie** [comment]
I'm also interested in other's opinions, but I'd like to reiterate: the bad practice here is using the same `id` attribute for DOM elements. IMHO, that is an implementation detail of shiny, not a concern for app authors. The problematic part is that _we_ put the same `id="foo"` attribute on two different elements, not that app authors use `input$foo` and `output$foo`. 

I've only found a few places in our documentation where we talk about inputs and outputs sharing a global namespace: both ([article](https://shiny.posit.co/r/articles/improve/modules/index.html), [package docs](https://rstudio.github.io/shiny/reference/NS.html)) are in sections related to Shiny modules. Neither are strongly worded or well-positioned enough to prevent this usage in real-world apps. And more importantly, the undefined behavior is theoretical, in practice our bindings work as intended in this situation.

IMHO, the first iteration of the error console should not break apps that currently work. This PR as it is now, covers both the current state of Shiny and the future world where we've changed how input and output IDs are stored on the bound elements.

I think augmenting the console to handle non-error messages is an excellent idea and would be broadly useful. That'd be great work to take up in a follow up PR.

**Comment by nstrayer** [comment]
I wonder if maybe the PR should be split into two parts: 
1. Fixing the objectively broken behavior regarding the `insertUI` and `removeUI` binding logic and 
2. fixing the more controversial shared ID problems. 

Currently, the changes are a bit spread out and I think it would be good to let 1's fix go through quickly without being dragged down by 2.

**Review by wch — APPROVED** [review]

**Comment by wch** [comment]
Merging this now to fix the bug with `insertUI`, but I'll file an issue to come back to overlapping input/output IDs, and enabling this only for local development.

File: srcts/src/shiny/bind.ts [hunk 14]
```diff
@@ -47,45 +47,57 @@ function valueChangeCallback(
...
   function checkValidity():
     | { status: "error"; error: ShinyClientError }
     | { status: "ok" } {
-    const duplicateIds: IdToBindingTypes = new Map();
+    type BindingCounts = { [T in BindingTypes]: number };
+    const duplicateIds = new Map<string, BindingCounts>();
+
+    // count duplicate IDs of each binding type
+    bindings.forEach((idTypes, id) => {
+      const counts: { [T in BindingTypes]: number } = { input: 0, output: 0 };
```
[the remark this answers is not in the document]
Comment (gadenbuie) [reply srcts/src/shiny/bind.ts:88]: Oh we should have removed the `BindingCounts` type since the definition above is more concise and would expand automatically if we added new binding types. Sorry, this change was made via the suggestion interface, so this was an oversight.
