### PR TITLE
Skip timer tests on CRAN and fix empty vector comparison

### LINKED ISSUE #4326: bug(CRAN): Fix failing dev tests
From CRAN:

```
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_shiny.html>.

Please correct before 2025-12-17 to safely retain your package on CRAN.

The CRAN Team
```

Details from just after 1.12.0 release:

```
Check Details
Version: 1.12.0
Check: tests
Result: ERROR 
    Running ‘testthat.R’ [100s/394s]
  Running the tests in ‘tests/testthat.R’ failed.
  Complete output:
    > library(testthat)
    > library(shiny)
    > 
    > test_check("shiny")
    Saving _problems/test-timer-35.R
    [ FAIL 1 | WARN 0 | SKIP 22 | PASS 1981 ]
    
    ══ Skipped tests (22) ══════════════════════════════════════════════════════════
    • File system is not case-sensitive (1): 'test-app.R:36:5'
    • I'm not sure of a great way to test this without timers. (1):
      'test-test-server.R:216:3'
    • Not testing in CI (1): 'test-devmode.R:17:3'
    • On CRAN (18): 'test-actionButton.R:59:1', 'test-busy-indication.R:1:1',
      'test-busy-indication.R:15:1', 'test-busy-indication.R:50:1',
      'test-otel-error.R:1:1', 'test-otel-mock.R:1:1', 'test-pkgdown.R:3:3',
      'test-reactivity.r:146:1', 'test-reactivity.r:1240:5',
      'test-reactivity.r:1240:5', 'test-stacks-deep.R:93:1',
      'test-stacks-deep.R:141:1', 'test-stacks.R:140:3', 'test-tabPanel.R:46:1',
      'test-tabPanel.R:66:1', 'test-tabPanel.R:73:1', 'test-tabPanel.R:83:1',
      'test-utils.R:177:3'
    • {shinytest2} is not installed (1): 'test-test-shinyAppTemplate.R:2:1'
    
    ══ Failed tests ════════════════════════════════════════════════════════════════
    ── Failure ('test-timer.R:35:3'): Unscheduling works ───────────────────────────
    Expected `timerCallbacks$.times` to be identical to `origTimes`.
    Differences:
    `attr(actual, 'row.names')` is an integer vector ()
    `attr(expected, 'row.names')` is a character vector ()
    
    
    [ FAIL 1 | WARN 0 | SKIP 22 | PASS 1981 ]
    Error:
    ! Test failures.
    Execution halted
Flavor: [r-devel-linux-x86_64-fedora-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/shiny-00check.html)

Version: 1.12.0
Check: tests
Result: ERROR 
    Running ‘testthat.R’ [94s/141s]
  Running the tests in ‘tests/testthat.R’ failed.
  Complete output:
    > library(testthat)
    > library(shiny)
    > 
    > test_check("shiny")
    Saving _problems/test-timer-35.R
    [ FAIL 1 | WARN 0 | SKIP 22 | PASS 1981 ]
    
    ══ Skipped tests (22) ══════════════════════════════════════════════════════════
    • File system is not case-sensitive (1): 'test-app.R:36:5'
    • I'm not sure of a great way to test this without timers. (1):
      'test-test-server.R:216:3'
    • Not testing in CI (1): 'test-devmode.R:17:3'
    • On CRAN (18): 'test-actionButton.R:59:1', 'test-busy-indication.R:1:1',
      'test-busy-indication.R:15:1', 'test-busy-indication.R:50:1',
      'test-otel-error.R:1:1', 'test-otel-mock.R:1:1', 'test-pkgdown.R:3:3',
      'test-reactivity.r:146:1', 'test-reactivity.r:1240:5',
      'test-reactivity.r:1240:5', 'test-stacks-deep.R:93:1',
      'test-stacks-deep.R:141:1', 'test-stacks.R:140:3', 'test-tabPanel.R:46:1',
      'test-tabPanel.R:66:1', 'test-tabPanel.R:73:1', 'test-tabPanel.R:83:1',
      'test-utils.R:177:3'
    • Refactor test for next release (1): 'test-test-shinyAppTemplate.R:3:1'
    
    ══ Failed tests ════════════════════════════════════════════════════════════════
    ── Failure ('test-timer.R:35:3'): Unscheduling works ───────────────────────────
    Expected `timerCallbacks$.times` to be identical to `origTimes`.
    Differences:
    `attr(actual, 'row.names')` is an integer vector ()
    `attr(expected, 'row.names')` is a character vector ()
    
    
    [ FAIL 1 | WARN 0 | SKIP 22 | PASS 1981 ]
    Error:
    ! Test failures.
    Execution halted
```

### PR DESCRIPTION
**Pull request by schloerke**
Fixes #4326 

Added skip_on_cran() to avoid running tests on CRAN due to issues with integer(0) vs character(0) comparisons. Updated unscheduling test to handle empty vector cases and prevent problematic comparisons. Reference: rstudio/shiny#4326.

Important changes for this PR: https://github.com/rstudio/shiny/pull/4327/files#diff-f9e9fa0d0c9623d7090206c75b9202e7603d333980f9675272959fb14cecad10

### CODE REVIEW

File: tests/testthat/test-timer.R [hunk 1]
```diff
@@ -1,3 +1,8 @@
+# Dev CRAN had some issues with comparisons between integer(0) and character(0)
+# Skipping tests on CRAN as CI is enough to verify functionality
+# Related: https://github.com/rstudio/shiny/issues/4326
+skip_on_cran()
```
Comment (cpsievert) [inline tests/testthat/test-timer.R:4]: Just confirming -- do we want to skip this entire file on CRAN?

Comment (schloerke) [reply tests/testthat/test-timer.R:4]: Yes. All structures are made by us within Shiny except for R6 classes. 

Therefore, it's only logic checks for us, which can be done "not on CRAN" as revdep checks wouldn't catch anything. I doubt R6 would _only_ break this class if it ever updated.
